server:
  port: 9090
spring:
  application:
    name: order-service
  zipin:
    base-url: http://loacalhost:9411/
    sender:
      type: web     #数据传输方式，web表示以Http提交的形式向服务器端发送数据
  sleuth:
    sampler:
      probability: 1.0 #收集数据百分比。默认是0.1
eureka:
  instance:
    #hostname: cluster01 # 主机名称，不配置的时候根据操作系统主机名获取
    prefer-ip-address: true #是否使用ip地址进行服务器注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #ip+port
  client:
    service-url:
      #defaultZone: http://localhost:8000/eureka/  #单机版
      defaultZone: http://root:123456@localhost:8001/eureka/,http://root:123456@localhost:8002/eureka/ #集群版

