server:
  port: 8000

eureka:
  instance:
    hostname: localhost # 主机名称，不配置的时候根据操作系统主机名获取
  client:
    register-with-eureka: false #是否将自己注册到注册中心，默认为true，单机情况下需要设置为false
    fetch-registry: false #是否从注册中心获取服务注册信息，默认为true,单机情况下需要设置为false
    service-url:
      defaultZone: http://localhost:8000/eureka/
